import { JsonLd } from "@/components/seo/JsonLd";
import { siteConfig, localizedPath, type PublicLocale } from "@/config/site";
export function GlobalSchemas({ locale }: { locale: PublicLocale }) { const url = `${siteConfig.url}${localizedPath(locale)}`; return <JsonLd data={[
  { "@context": "https://schema.org", "@type": "Organization", name: siteConfig.name, url: siteConfig.url, logo: `${siteConfig.url}/icons/icon-512x512.png`, founder: { "@type": "Person", name: siteConfig.creator } },
  { "@context": "https://schema.org", "@type": "WebSite", name: siteConfig.name, url, inLanguage: locale, potentialAction: { "@type": "SearchAction", target: `${siteConfig.url}${localizedPath(locale, "search")}?q={search_term_string}`, "query-input": "required name=search_term_string" } },
  { "@context": "https://schema.org", "@type": "SoftwareApplication", name: siteConfig.name, applicationCategory: "SportsApplication", operatingSystem: "Web, Windows, macOS, Linux, Android, iOS", url, inLanguage: locale, description: siteConfig.description },
]} />; }
export function PageSchema({ locale, path, title, description }: { locale: PublicLocale; path: string; title: string; description: string }) { return <JsonLd data={{ "@context": "https://schema.org", "@type": "WebPage", name: title, description, url: `${siteConfig.url}${localizedPath(locale, path)}`, inLanguage: locale, breadcrumb: { "@type": "BreadcrumbList", itemListElement: path.split("/").filter(Boolean).map((segment, index, all) => ({ "@type": "ListItem", position: index + 1, name: segment.replaceAll("-", " "), item: `${siteConfig.url}${localizedPath(locale, all.slice(0, index + 1).join("/"))}` })) } }} />; }
export function FaqSchema({ items }: { items: { question: string; answer: string }[] }) { return <JsonLd data={{ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: items.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) }} />; }
