"use client";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { CheckCircle2, Dumbbell, ShipWheel, Upload, X } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { ProtectedPage } from "@/components/ProtectedPage";
import { useAuth } from "@/providers/AuthProvider";
import { createAnalysis, updateAnalysis } from "@/services/analysis-service";
import { uploadAnalysisVideo, validateAnalysisVideo } from "@/services/storage-service";
import type { AnalysisEnvironment } from "@/types/analysis";

function NewAnalysisContent() {
  const { profile } = useAuth(); const router = useRouter(); const params = useSearchParams();
  const requested = params.get("environment"); const [environment, setEnvironment] = useState<AnalysisEnvironment>(requested === "ergometer" ? "ergometer" : "boat");
  const [athleteId, setAthleteId] = useState(""); const [athleteName, setAthleteName] = useState(""); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [progress, setProgress] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (profile?.role === "athlete") { setAthleteId(profile.uid); setAthleteName(`${profile.firstName} ${profile.lastName}`.trim()); } }, [profile]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  if (!profile) return null;
  const submit = async () => { if (!file || !athleteId || !athleteName.trim()) { setError("Sélectionnez un athlète et une vidéo."); return; } setBusy(true); setError(""); try { const id = await createAnalysis({ athleteId, athleteName: athleteName.trim(), environment, sourceType: "video", profile, fileName: file.name }); const uploaded = await uploadAnalysisVideo(id, file, setProgress); await updateAnalysis(id, { videoUrl: uploaded.url, storagePath: uploaded.path, status: "processing" }); router.replace(`/analyses/${id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Impossible d’importer cette vidéo."); setBusy(false); } };
  return <AppShell title="Nouvelle analyse" subtitle="Assistant d’import vidéo"><div className="step-card"><span className="step-number">1</span><h2>Athlète analysé</h2>{profile.role === "athlete" ? <p className="selection-confirm"><CheckCircle2 />{athleteName}</p> : <div className="form-grid"><label className="plain-field">Identifiant Firestore de l’athlète<input value={athleteId} onChange={(e) => setAthleteId(e.target.value)} /></label><label className="plain-field">Nom de l’athlète<input value={athleteName} onChange={(e) => setAthleteName(e.target.value)} /></label></div>}<p className="helper-text">Les sélecteurs club/coach seront alimentés par les associations Firestore validées.</p></div><div className="step-card"><span className="step-number">2</span><h2>Environnement</h2><div className="choice-grid"><button className={environment === "boat" ? "selected" : ""} onClick={() => setEnvironment("boat")}><ShipWheel /><strong>Analyse en bateau</strong><small>Posture, rythme, trajectoire, stabilité et symétrie.</small></button><button className={environment === "ergometer" ? "selected" : ""} onClick={() => setEnvironment("ergometer")}><Dumbbell /><strong>Ergomètre</strong><small>Angles, séquence jambes-tronc-bras, cadence et puissance.</small></button></div></div><div className="step-card"><span className="step-number">3</span><h2>Vidéo</h2>{file ? <div className="video-preview"><video controls src={preview} /><div><strong>{file.name}</strong><small>{(file.size / 1024 / 1024).toFixed(1)} Mo</small><button disabled={busy} onClick={() => { URL.revokeObjectURL(preview); setFile(null); setPreview(""); }}><X />Retirer</button></div></div> : <label className="upload-zone"><Upload /><strong>Choisir une vidéo</strong><small>MP4, MOV ou WebM · 250 Mo maximum</small><input type="file" accept="video/mp4,video/quicktime,video/webm" onChange={(e) => { const selected = e.target.files?.[0]; if (!selected) return; try { validateAnalysisVideo(selected); setFile(selected); setPreview(URL.createObjectURL(selected)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Fichier invalide."); } }} /></label>}{busy && <div className="progress-track"><span style={{ width: `${progress}%` }} /><small>{progress}% importé</small></div>}{error && <div className="error-card">{error}</div>}<button className="button primary submit-analysis" disabled={busy || !file} onClick={() => void submit()}>{busy ? "Import en cours…" : "Importer et lancer l’analyse"}</button></div></AppShell>;
}
export default function NewAnalysisPage() { return <ProtectedPage><NewAnalysisContent /></ProtectedPage>; }
