import Link from "next/link";
import { JsonLd } from "@/components/seo/JsonLd";
import { FaqSchema } from "@/components/seo/Schemas";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { blogArticles, type BlogArticle } from "@/content/blog";
import { localizedPath, siteConfig, type PublicLocale } from "@/config/site";

export function BlogIndex({ locale }: { locale: PublicLocale }) { return <main className="public-main"><Breadcrumbs locale={locale} path="blog" current="Blog" /><section className="public-page-hero"><span>Ressources</span><h1>Conseils aviron, biomécanique et analyse vidéo</h1><p>Des guides pratiques pour filmer, comprendre et améliorer la technique sur ergomètre comme sur l’eau.</p></section><section className="blog-grid">{blogArticles.map((article) => <article key={article.slug}><span>{article.category} · {article.readingMinutes} min</span><h2><Link href={localizedPath(locale, `blog/${article.slug}`)}>{article.title}</Link></h2><p>{article.description}</p><Link href={localizedPath(locale, `blog/${article.slug}`)}>Lire l’article →</Link></article>)}</section></main>; }

export function BlogPost({ locale, article }: { locale: PublicLocale; article: BlogArticle }) { const url = `${siteConfig.url}${localizedPath(locale, `blog/${article.slug}`)}`; return <><JsonLd data={{ "@context":"https://schema.org", "@type":"Article", headline:article.title, description:article.description, datePublished:article.publishedAt, dateModified:article.updatedAt, mainEntityOfPage:url, author:{"@type":"Person",name:siteConfig.creator}, publisher:{"@type":"Organization",name:siteConfig.name,url:siteConfig.url} }} /><FaqSchema items={article.faq} /><main className="public-main article-page"><Breadcrumbs locale={locale} path={`blog/${article.slug}`} current={article.title} /><header><span>{article.category} · {article.readingMinutes} min</span><h1>{article.title}</h1><p>{article.description}</p><time dateTime={article.updatedAt}>Mis à jour le {new Intl.DateTimeFormat(locale).format(new Date(article.updatedAt))}</time></header>{article.sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}<section><h2>Questions fréquentes</h2>{article.faq.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section></main></>; }
