import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { PageSchema } from "@/components/seo/Schemas";
import { ContactForm } from "@/components/public/ContactForm";
import { getDictionary } from "@/i18n/dictionaries";
import { localizedPath, type PublicLocale } from "@/config/site";
import type { PublicPageContent } from "@/content/public-pages";

export function PublicPage({ locale, page }: { locale: PublicLocale; page: PublicPageContent }) { const d = getDictionary(locale); const title = page.title[locale]; const description = page.description[locale]; const isLegal = page.group === "legal"; return <><PageSchema locale={locale} path={page.path} title={title} description={description} /><main className="public-main"><Breadcrumbs locale={locale} path={page.path} current={title} /><section className="public-page-hero"><span>{page.group}</span><h1>{title}</h1><p>{description}</p>{!isLegal && <div><Link className="button primary" href="/inscription">{d.common.startAnalysis}</Link><Link className="button ghost" href={localizedPath(locale,"contact")}>{d.common.contact}</Link></div>}</section>{page.path === "contact" ? <ContactForm locale={locale} /> : <section className="public-content-grid">{page.points[locale].map((point, index) => <article key={point}><span><CheckCircle2 /></span><h2>{point}</h2><p>{detailText(locale, page.group, index)}</p></article>)}</section>}{page.path === "pricing" && <div className="honesty-note">{locale === "fr" ? "Aucun tarif fictif n’est affiché. Contactez-nous pour préparer une offre adaptée à votre structure." : locale === "en" ? "No fabricated price is displayed. Contact us to prepare an offer for your organization." : "لا نعرض أسعاراً وهمية. تواصل معنا لإعداد عرض مناسب لمؤسستك."}</div>}{isLegal && <LegalDetails locale={locale} kind={page.path} />}<section className="public-cta"><h2>{locale === "fr" ? "Prêt à structurer votre analyse technique ?" : locale === "en" ? "Ready to structure your technical analysis?" : "هل أنت مستعد لتنظيم تحليلك التقني؟"}</h2><Link className="button primary" href="/inscription">{d.common.startAnalysis}<ArrowRight /></Link></section></main></>; }

function detailText(locale: PublicLocale, group: PublicPageContent["group"], index: number) { const texts = { fr: ["Des informations structurées, compréhensibles et reliées à de vrais profils autorisés.", "Une interface responsive utilisable sur ordinateur, tablette et téléphone.", "Une approche progressive qui distingue les fonctions opérationnelles des modèles IA encore à connecter."], en: ["Structured information connected to real authorized profiles.", "A responsive interface for desktop, tablet and mobile.", "A progressive approach that distinguishes operational tools from AI models still to be integrated."], ar: ["معلومات منظمة ومرتبطة بملفات حقيقية مصرح بها.", "واجهة متجاوبة للحاسوب واللوحي والهاتف.", "منهج تدريجي يميز بين الأدوات العاملة ونماذج الذكاء الاصطناعي التي ما زالت قيد الدمج."] }; return texts[locale][index] ?? texts[locale][0]; }
function LegalDetails({ locale, kind }: { locale: PublicLocale; kind: string }) { const content = locale === "fr" ? ["RowMotion AI peut traiter des données de compte, profils sportifs, vidéos importées, mesures biomécaniques, commentaires de coach et associations de club.", "Les données privées ne sont jamais intégrées à la recherche publique. Les outils de mesure non essentiels nécessitent un consentement préalable.", "Vous pouvez demander l’accès, la rectification ou la suppression selon les règles applicables et les contraintes de conservation."] : locale === "en" ? ["RowMotion AI may process account data, sports profiles, imported videos, biomechanics measurements, coach comments and club links.", "Private data is never included in public search. Non-essential measurement tools require prior consent.", "You may request access, correction or deletion subject to applicable rules and retention obligations."] : ["قد تعالج RowMotion AI بيانات الحساب والملفات الرياضية والفيديوهات والقياسات وملاحظات المدرب وروابط النادي.", "لا تُدرج البيانات الخاصة في البحث العام، وتتطلب أدوات القياس غير الضرورية موافقة مسبقة.", "يمكنك طلب الوصول أو التصحيح أو الحذف وفق القواعد المطبقة ومتطلبات الاحتفاظ."]; return <section className="legal-content"><h2>{kind === "privacy" ? "Données et confidentialité" : kind === "cookies" ? "Consentement et stockage" : "Utilisation de la plateforme"}</h2>{content.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>; }
