"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, CheckCircle2, Download, Gauge, MessageSquare, RotateCcw } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { ProtectedPage } from "@/components/ProtectedPage";
import { useAuth } from "@/providers/AuthProvider";
import { getAnalysis, updateAnalysis } from "@/services/analysis-service";
import type { RowingAnalysis } from "@/types/analysis";

function AnalysisDetail({ analysisId }: { analysisId: string }) {
  const { profile } = useAuth(); const [analysis, setAnalysis] = useState<RowingAnalysis | null>(null); const [error, setError] = useState(""); const [note, setNote] = useState("");
  useEffect(() => { if (!profile) return; void getAnalysis(analysisId, profile).then((value) => { setAnalysis(value); setNote(value.coachComment ?? ""); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Analyse introuvable.")); }, [analysisId, profile]);
  if (!profile) return null;
  return <AppShell title="Détail de l’analyse" subtitle={analysis?.athleteName ?? "Chargement"}><Link className="back-link" href="/analyses"><ArrowLeft />Toutes les analyses</Link>{error ? <div className="error-card">{error}</div> : !analysis ? <div className="loading-card">Chargement de l’analyse…</div> : <><section className="analysis-hero-card"><div><span className={`status-pill ${analysis.status}`}>{analysis.status}</span><h2>{analysis.environment === "boat" ? "Analyse en bateau" : "Analyse sur ergomètre"}</h2><p>{analysis.sourceType === "video" ? "Vidéo importée" : "Session en direct"} · {analysis.fileName ?? "Sans fichier"}</p></div><div className="score-ring"><strong>{analysis.technicalScore ?? "—"}</strong><small>/100</small></div></section>{analysis.status === "processing" && <div className="notice-card"><Gauge /><div><strong>Analyse en préparation</strong><p>La vidéo est enregistrée. Le moteur biomécanique réel doit maintenant traiter le fichier.</p></div></div>}{analysis.status === "failed" && <div className="error-card"><AlertTriangle />L’analyse a échoué. <button onClick={() => void updateAnalysis(analysis.id, { status: "processing" }).then(() => setAnalysis({ ...analysis, status: "processing" }))}><RotateCcw />Réessayer</button></div>}{analysis.videoUrl && <video className="analysis-video" controls src={analysis.videoUrl} />}<div className="metrics-grid">{Object.entries(analysis.metrics).map(([key, value]) => <article key={key}><small>{key}</small><strong>{value ?? "—"}</strong></article>)}</div><div className="detail-columns"><section className="content-card"><h2><AlertTriangle />Erreurs détectées</h2>{analysis.errors.length ? <ul>{analysis.errors.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Aucune erreur calculée pour le moment.</p>}</section><section className="content-card"><h2><CheckCircle2 />Recommandations</h2>{analysis.recommendations.length ? <ul>{analysis.recommendations.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Disponibles après traitement biomécanique.</p>}</section></div>{["coach", "club_admin", "superadmin"].includes(profile.role) && <section className="content-card"><h2><MessageSquare />Note coach</h2><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Ajouter une observation technique…" /><button className="button primary" onClick={() => void updateAnalysis(analysis.id, { coachComment: note }).then(() => setAnalysis({ ...analysis, coachComment: note }))}>Enregistrer la note</button></section>}<div className="page-actions"><Link className="button ghost" href={`/rapports?analysis=${analysis.id}`}><Download />Préparer le rapport</Link></div></>}</AppShell>;
}
export default function AnalysisDetailPage({ params }: { params: Promise<{ analysisId: string }> }) { const { analysisId } = use(params); return <ProtectedPage><AnalysisDetail analysisId={analysisId} /></ProtectedPage>; }
