export interface BlogArticle { slug: string; title: string; description: string; publishedAt: string; updatedAt: string; category: string; tags: string[]; readingMinutes: number; sections: { title: string; paragraphs: string[] }[]; faq: { question: string; answer: string }[] }
const article = (slug: string, title: string, description: string, category: string, tags: string[], sections: BlogArticle["sections"], faq: BlogArticle["faq"]): BlogArticle => ({ slug, title, description, category, tags, sections, faq, publishedAt: "2026-07-20", updatedAt: "2026-07-20", readingMinutes: Math.max(5, sections.length * 2) });
export const blogArticles: BlogArticle[] = [
  article("ameliorer-technique-aviron-analyse-video", "Comment améliorer sa technique d’aviron avec l’analyse vidéo", "Une méthode concrète pour filmer, observer et corriger le coup d’aviron sans confondre ressenti et mesure.", "Analyse vidéo", ["analyse vidéo aviron", "technique rameur"], [
    { title: "Filmer une séquence exploitable", paragraphs: ["Placez la caméra perpendiculairement au rameur, à hauteur du mouvement et suffisamment loin pour conserver les pieds, le siège, les mains et la tête dans le cadre. Une image stable et bien éclairée facilite l’observation des articulations.", "Sur l’eau, choisissez une prise de vue qui limite les changements de perspective. Notez le type de bateau, le côté du rameur et les conditions afin de comparer des séances réellement comparables."] },
    { title: "Observer une priorité à la fois", paragraphs: ["Commencez par la séquence globale : jambes, tronc puis bras pendant la propulsion, et l’ordre inverse au retour. Analysez ensuite les angles et la régularité au lieu de corriger dix éléments simultanément.", "Une mesure automatique reste un indicateur technique. Elle doit être interprétée avec le coach, le contexte de la séance et les caractéristiques de l’athlète."] },
    { title: "Comparer dans le temps", paragraphs: ["Utilisez un cadrage proche, une intensité similaire et les mêmes repères. Une amélioration utile apparaît dans la répétabilité du mouvement, pas seulement dans un meilleur score isolé."] },
  ], [{ question: "Une seule vidéo suffit-elle ?", answer: "Elle permet un premier état des lieux, mais plusieurs coups et plusieurs séances sont nécessaires pour évaluer la régularité." }]),
  article("erreurs-frequentes-ergometre", "Les erreurs les plus fréquentes sur ergomètre", "Reconnaître les défauts de séquence, de posture et de retour sur un ergomètre d’aviron.", "Ergomètre", ["analyse ergomètre", "Concept2"], [
    { title: "Tirer les bras trop tôt", paragraphs: ["Lorsque les bras se fléchissent avant que la poussée des jambes soit suffisamment avancée, la chaîne de transmission perd en efficacité. Gardez les bras longs au début de la propulsion."] },
    { title: "Ouvrir le dos trop tôt", paragraphs: ["Une ouverture précoce du tronc peut déplacer la charge vers le bas du dos. Cherchez une poussée de jambes stable avant d’accompagner avec le tronc."] },
    { title: "Précipiter le retour", paragraphs: ["Le retour doit laisser le temps aux mains de s’éloigner, au tronc de revenir puis aux genoux de se fléchir. Un ratio plus calme favorise le placement à l’attaque."] },
  ], [{ question: "Faut-il copier un angle universel ?", answer: "Non. Les repères doivent être adaptés à la morphologie, à la mobilité, au niveau et à l’objectif de séance." }]),
  article("analyser-phase-attaque-aviron", "Comment analyser la phase d’attaque en aviron", "Les repères visuels et biomécaniques pour une attaque longue, stable et contrôlée.", "Technique", ["phase attaque aviron", "angle genou"], [
    { title: "Vérifier la position", paragraphs: ["À l’attaque, observez l’alignement de la tête, la stabilité du tronc, la flexion des genoux et la disponibilité des épaules. La longueur ne doit pas être obtenue par un effondrement du dos."] },
    { title: "Contrôler le changement de direction", paragraphs: ["Le passage du retour à la propulsion doit rester fluide. Une accélération brutale du siège ou une ouverture immédiate du dos révèle souvent une séquence instable."] },
    { title: "Relier l’image au ressenti", paragraphs: ["Associez une consigne simple à la vidéo, puis vérifiez quelques coups plus tard si la modification est reproductible sans perte de rythme."] },
  ], [{ question: "Quel angle de caméra utiliser ?", answer: "Une vue latérale est utile pour les angles et la séquence ; une vue frontale complète l’analyse de la symétrie." }]),
  article("synchronisation-jambes-tronc-bras", "Synchronisation jambes, tronc et bras", "Comprendre la transmission des forces pendant la propulsion et l’ordre du retour.", "Biomécanique", ["jambes tronc bras", "rowing biomechanics"], [
    { title: "Construire la propulsion", paragraphs: ["Les jambes initient la production de force pendant que le tronc transmet et que les bras restent disponibles. Les actions se chevauchent progressivement plutôt que de former trois blocs rigides."] },
    { title: "Organiser le retour", paragraphs: ["Après la fin de coup, les mains s’éloignent, le tronc se replace puis le siège avance. Cet ordre crée de l’espace et évite que les genoux bloquent les mains."] },
    { title: "Mesurer sans simplifier à l’excès", paragraphs: ["Les vitesses articulaires et les instants de transition aident à comparer les coups, mais la qualité dépend aussi de la charge, de la cadence et de la fatigue."] },
  ], [{ question: "Les actions doivent-elles être totalement séparées ?", answer: "Non. Une coordination efficace comporte des transitions progressives adaptées à l’athlète et à la cadence." }]),
  article("biomecanique-coup-aviron", "Analyse biomécanique du coup d’aviron", "Angles, trajectoires, phases et limites d’une analyse biomécanique appliquée à l’aviron.", "Biomécanique", ["biomécanique aviron", "angles articulaires"], [
    { title: "Décrire le mouvement", paragraphs: ["Une analyse biomécanique décrit des positions, distances, vitesses et séquences. Les angles du genou, de la hanche, du dos et du coude donnent des repères lorsqu’ils sont calculés avec un protocole stable."] },
    { title: "Segmenter les phases", paragraphs: ["La distinction entre attaque, propulsion, fin de coup et retour permet de comparer les durées et d’identifier l’endroit où la coordination change."] },
    { title: "Respecter les limites", paragraphs: ["Une vidéo monoculaire comporte des erreurs de perspective et d’occlusion. L’outil ne remplace ni un diagnostic médical ni l’expertise du coach."] },
  ], [{ question: "La biomécanique donne-t-elle une technique parfaite ?", answer: "Non. Elle fournit des indicateurs objectifs qui doivent être interprétés dans le contexte sportif." }]),
  article("ameliorer-synchronisation-equipage", "Comment améliorer la synchronisation d’un équipage", "Une démarche pour aligner les phases sans effacer les caractéristiques individuelles.", "Équipage", ["synchronisation équipage aviron", "crew rowing"], [
    { title: "Choisir des repères communs", paragraphs: ["Comparez les changements de direction, le début de propulsion, la fin de jambes et la sortie. Des repères partagés rendent les retours vidéo plus précis."] },
    { title: "Observer le rythme collectif", paragraphs: ["La synchronisation ne signifie pas seulement partir ensemble. Elle concerne aussi la distribution du temps entre propulsion et retour et la façon dont l’équipage accélère le bateau."] },
    { title: "Corriger par petits groupes", paragraphs: ["Travaillez une paire ou une ligne à la fois, puis réintégrez le bateau complet. La vidéo aide à distinguer une différence locale d’un problème global."] },
  ], [{ question: "Faut-il comparer uniquement les poignées ?", answer: "Non. Le siège, le tronc, les mains et les changements de direction apportent des informations complémentaires." }]),
  article("ergometre-ou-bateau-differences-techniques", "Ergomètre ou bateau : quelles différences techniques ?", "Ce que l’ergomètre permet de travailler et ce qui reste spécifique au bateau.", "Entraînement", ["ergomètre bateau", "technique aviron"], [
    { title: "Un environnement stable", paragraphs: ["L’ergomètre facilite la répétition, le contrôle de l’intensité et la vue latérale. Il est utile pour la séquence, la cadence et la régularité."] },
    { title: "Les contraintes de l’eau", paragraphs: ["Dans le bateau, l’équilibre, le placement de la pelle, les mouvements latéraux et la synchronisation ajoutent des contraintes absentes de la machine."] },
    { title: "Transférer avec prudence", paragraphs: ["Une amélioration sur ergomètre doit être vérifiée sur l’eau. Conservez une intention technique commune tout en adaptant les repères au matériel et à l’équipage."] },
  ], [{ question: "L’ergomètre reproduit-il exactement le bateau ?", answer: "Non. Il reproduit une partie de la chaîne de propulsion, sans toutes les contraintes d’équilibre et de pelle." }]),
  article("filmer-rameur-analyse-ia", "Comment filmer correctement un rameur pour une analyse IA", "Cadrage, lumière, stabilité et confidentialité pour obtenir une vidéo exploitable.", "Guide", ["filmer rameur", "analyse IA aviron"], [
    { title: "Préparer le cadre", paragraphs: ["Nettoyez l’objectif, utilisez une résolution suffisante et placez tout le corps dans l’image. Évitez le contre-jour, les vêtements trop amples et les objets qui masquent les articulations."] },
    { title: "Stabiliser la caméra", paragraphs: ["Utilisez un trépied ou un support fixe. Une caméra qui suit le rameur peut être utile sur l’eau, mais les changements de perspective compliquent la comparaison des angles."] },
    { title: "Protéger les personnes", paragraphs: ["Obtenez l’autorisation des personnes filmées, limitez les éléments identifiants dans le cadre et utilisez uniquement les espaces sécurisés prévus par la plateforme."] },
  ], [{ question: "Quels formats sont acceptés ?", answer: "La première version accepte MP4, MOV et WebM, avec une limite indiquée dans l’assistant d’import." }]),
];
export function getBlogArticle(slug: string) { return blogArticles.find((item) => item.slug === slug); }
