import type { PublicLocale } from "@/config/site";

export interface PublicPageContent { path: string; group: "feature" | "solution" | "rowing" | "resource" | "company" | "legal"; title: Record<PublicLocale, string>; description: Record<PublicLocale, string>; points: Record<PublicLocale, readonly string[]> }
const t = (fr: string, en: string, ar: string) => ({ fr, en, ar });
const genericPoints = {
  feature: { fr: ["Mesures techniques lisibles", "Suivi sécurisé par athlète", "Résultats adaptés aux coachs"], en: ["Readable technical metrics", "Secure athlete tracking", "Coach-ready results"], ar: ["مقاييس تقنية واضحة", "متابعة آمنة لكل رياضي", "نتائج مناسبة للمدربين"] },
  solution: { fr: ["Organisation des profils", "Analyses centralisées", "Progression mesurable"], en: ["Organized profiles", "Centralized analyses", "Measurable progress"], ar: ["تنظيم الملفات", "تحليلات مركزية", "تقدم قابل للقياس"] },
  rowing: { fr: ["Comprendre les phases du coup", "Identifier les erreurs techniques", "Construire un entraînement ciblé"], en: ["Understand stroke phases", "Identify technical errors", "Build focused training"], ar: ["فهم مراحل ضربة المجداف", "تحديد الأخطاء التقنية", "بناء تدريب موجه"] },
  resource: { fr: ["Conseils applicables", "Progression structurée", "Contenu dédié à l’aviron"], en: ["Actionable advice", "Structured progression", "Rowing-specific content"], ar: ["نصائح قابلة للتطبيق", "تقدم منظم", "محتوى خاص بالتجديف"] },
  company: { fr: ["Une plateforme conçue pour l’aviron", "Données traitées avec prudence", "Support des clubs et des coachs"], en: ["A platform built for rowing", "Data handled responsibly", "Support for clubs and coaches"], ar: ["منصة مصممة للتجديف", "معالجة مسؤولة للبيانات", "دعم الأندية والمدربين"] },
  legal: { fr: ["Transparence", "Protection des utilisateurs", "Utilisation responsable"], en: ["Transparency", "User protection", "Responsible use"], ar: ["الشفافية", "حماية المستخدم", "الاستخدام المسؤول"] },
} as const;
function page(path: string, group: PublicPageContent["group"], title: Record<PublicLocale,string>, description: Record<PublicLocale,string>, points = genericPoints[group]): PublicPageContent { return { path, group, title, description, points }; }

export const publicPages: PublicPageContent[] = [
  page("features", "feature", t("Fonctionnalités d’analyse pour l’aviron", "Rowing analysis features", "ميزات تحليل التجديف"), t("Découvrez les outils vidéo, directs et biomécaniques de RowMotion AI.", "Discover RowMotion AI video, live and biomechanics tools.", "اكتشف أدوات الفيديو والتحليل المباشر والميكانيكا الحيوية في RowMotion AI.")),
  page("features/video-analysis", "feature", t("Analyse vidéo d’aviron par IA", "AI rowing video analysis", "تحليل فيديو التجديف بالذكاء الاصطناعي"), t("Importez une vidéo MP4, MOV ou WebM pour préparer la détection du squelette, des angles et des phases.", "Import MP4, MOV or WebM video to prepare skeleton, angle and stroke-phase detection.", "ارفع فيديو MP4 أو MOV أو WebM لتحليل الهيكل والزوايا ومراحل الحركة.")),
  page("features/live-analysis", "feature", t("Analyse en direct avec la caméra", "Live camera analysis", "التحليل المباشر بالكاميرا"), t("Positionnez votre téléphone, choisissez l’athlète et lancez une session caméra avec des autorisations explicites.", "Position your phone, select the athlete and start a camera session with explicit permissions.", "ضع هاتفك واختر الرياضي وابدأ جلسة كاميرا بصلاحيات واضحة.")),
  page("features/ergometer-analysis", "feature", t("Analyse technique sur ergomètre", "Ergometer technique analysis", "التحليل التقني على جهاز التجديف"), t("Étudiez attaque, propulsion, fin de coup, retour, cadence et coordination jambes-tronc-bras.", "Study catch, drive, finish, recovery, stroke rate and legs-body-arms coordination.", "حلّل الالتقاط والدفع والنهاية والعودة والإيقاع وتنسيق الساقين والجذع والذراعين.")),
  page("features/boat-analysis", "feature", t("Analyse du rameur dans le bateau", "In-boat rowing analysis", "تحليل المجدف داخل القارب"), t("Analyse individuelle ou collective, bâbord ou tribord, synchronisation, équilibre et trajectoire.", "Individual or crew analysis for port or starboard, synchronization, balance and trajectory.", "تحليل فردي أو جماعي للميمنة أو الميسرة والتزامن والتوازن والمسار.")),
  page("features/crew-analysis", "feature", t("Analyse de synchronisation d’équipage", "Crew synchronization analysis", "تحليل تزامن الطاقم"), t("Comparez les phases et le rythme de plusieurs rameurs sans masquer les différences individuelles.", "Compare stroke phases and rhythm across rowers while preserving individual insight.", "قارن مراحل الحركة والإيقاع بين المجدفين مع الحفاظ على التحليل الفردي.")),
  page("features/ai-reports", "feature", t("Rapports techniques assistés par IA", "AI-assisted technical reports", "تقارير تقنية بمساعدة الذكاء الاصطناعي"), t("Centralisez mesures, erreurs, recommandations et commentaires du coach dans un rapport exploitable.", "Combine metrics, errors, recommendations and coach feedback in an actionable report.", "اجمع المقاييس والأخطاء والتوصيات وملاحظات المدرب في تقرير عملي.")),
  page("features/progress-tracking", "feature", t("Suivi de progression en aviron", "Rowing progress tracking", "متابعة تطور الأداء في التجديف"), t("Comparez les séances sans inventer de données et identifiez les tendances techniques réelles.", "Compare sessions without fabricated data and identify genuine technical trends.", "قارن الجلسات دون بيانات مصطنعة وحدد الاتجاهات التقنية الحقيقية.")),
  page("solutions", "solution", t("Solutions RowMotion AI", "RowMotion AI solutions", "حلول RowMotion AI"), t("Des espaces adaptés aux athlètes, coachs, clubs et fédérations.", "Workspaces for athletes, coaches, clubs and federations.", "مساحات مخصصة للرياضيين والمدربين والأندية والاتحادات.")),
  page("solutions/athletes", "solution", t("RowMotion AI pour les athlètes", "RowMotion AI for athletes", "RowMotion AI للرياضيين"), t("Importez vos séances, consultez votre coach et suivez votre progression technique.", "Import sessions, review coach feedback and track technical progress.", "ارفع جلساتك وراجع ملاحظات مدربك وتابع تقدمك التقني.")),
  page("solutions/coaches", "solution", t("Logiciel d’analyse pour coachs d’aviron", "Rowing analysis software for coaches", "برنامج تحليل لمدربي التجديف"), t("Gérez les athlètes autorisés, ajoutez des notes et comparez les analyses.", "Manage authorized athletes, add notes and compare analyses.", "أدر الرياضيين المصرح لهم وأضف الملاحظات وقارن التحليلات.")),
  page("solutions/clubs", "solution", t("Plateforme d’analyse pour clubs d’aviron", "Analysis platform for rowing clubs", "منصة تحليل لأندية التجديف"), t("Organisez coachs, athlètes, associations et statistiques dans un espace de club sécurisé.", "Organize coaches, athletes, links and statistics in a secure club workspace.", "نظّم المدربين والرياضيين والروابط والإحصاءات في مساحة آمنة للنادي.")),
  page("solutions/federations", "solution", t("Données techniques pour fédérations", "Technical data for federations", "بيانات تقنية للاتحادات"), t("Préparez une vision multi-clubs cohérente avec des permissions et des données structurées.", "Prepare a consistent multi-club view with permissions and structured data.", "أنشئ رؤية موحدة لعدة أندية بصلاحيات وبيانات منظمة.")),
  page("rowing", "rowing", t("Comprendre la technique d’aviron", "Understand rowing technique", "فهم تقنية التجديف"), t("Ressources sur le coup d’aviron, la coordination et la biomécanique.", "Resources on the rowing stroke, coordination and biomechanics.", "موارد حول ضربة التجديف والتنسيق والميكانيكا الحيوية.")),
  page("rowing/ergometer", "rowing", t("Technique d’aviron sur ergomètre", "Ergometer rowing technique", "تقنية التجديف على الجهاز"), t("Comprenez les quatre phases et la coordination efficace sur ergomètre.", "Understand the four phases and efficient ergometer coordination.", "افهم المراحل الأربع والتنسيق الفعال على جهاز التجديف.")),
  page("rowing/boat", "rowing", t("Technique d’aviron en bateau", "On-water rowing technique", "تقنية التجديف في القارب"), t("Posture, équilibre, trajectoire et synchronisation dans des conditions réelles.", "Posture, balance, trajectory and synchronization on the water.", "الوضعية والتوازن والمسار والتزامن في ظروف مائية حقيقية.")),
  page("rowing/sculling", "rowing", t("Technique de couple", "Sculling technique", "تقنية المجدافين"), t("Travaillez la symétrie, la hauteur des mains et le placement des pelles en couple.", "Develop symmetry, hand heights and blade placement in sculling.", "طوّر التماثل وارتفاع اليدين ووضع المجاديف في التجديف المزدوج.")),
  page("rowing/sweep-rowing", "rowing", t("Technique de pointe", "Sweep rowing technique", "تقنية المجداف الواحد"), t("Analysez les contraintes asymétriques et la contribution du rameur à l’équipage.", "Analyze asymmetric demands and each rower’s contribution to the crew.", "حلّل المتطلبات غير المتماثلة ومساهمة كل مجدف في الطاقم.")),
  page("rowing/crew-synchronization", "rowing", t("Synchronisation d’un équipage", "Crew synchronization", "تزامن طاقم التجديف"), t("Alignez les temps de phase tout en respectant les caractéristiques de chaque rameur.", "Align phase timing while respecting each rower’s characteristics.", "وحّد توقيت المراحل مع احترام خصائص كل مجدف.")),
  page("rowing/biomechanics", "rowing", t("Biomécanique du coup d’aviron", "Biomechanics of the rowing stroke", "الميكانيكا الحيوية لضربة التجديف"), t("Découvrez les angles, forces et séquences utiles à une analyse technique responsable.", "Explore angles, forces and sequences used in responsible technical analysis.", "اكتشف الزوايا والقوى والتسلسلات المستخدمة في التحليل التقني المسؤول.")),
  page("resources", "resource", t("Ressources pour progresser en aviron", "Resources for rowing improvement", "موارد لتطوير التجديف"), t("Guides, exercices et contenus biomécaniques pour structurer l’entraînement.", "Guides, drills and biomechanics content for structured training.", "أدلة وتمارين ومحتوى ميكانيكي حيوي لتنظيم التدريب.")),
  page("resources/training-plans", "resource", t("Plans d’entraînement d’aviron", "Rowing training plans", "خطط تدريب التجديف"), t("Organisez technique, intensité et récupération selon des objectifs mesurables.", "Organize technique, intensity and recovery around measurable goals.", "نظّم التقنية والشدة والاستشفاء وفق أهداف قابلة للقياس.")),
  page("resources/rowing-drills", "resource", t("Exercices techniques d’aviron", "Rowing technique drills", "تمارين تقنية للتجديف"), t("Sélection d’exercices pour la séquence, le rythme et le contrôle du retour.", "Drills for sequencing, rhythm and recovery control.", "تمارين للتسلسل والإيقاع والتحكم في مرحلة العودة.")),
  page("resources/biomechanics", "resource", t("Guide de biomécanique de l’aviron", "Rowing biomechanics guide", "دليل الميكانيكا الحيوية للتجديف"), t("Interprétez les mesures sans confondre indicateur technique et diagnostic médical.", "Interpret metrics without confusing technical indicators with medical diagnosis.", "فسّر المقاييس دون الخلط بين المؤشر التقني والتشخيص الطبي.")),
  page("resources/guides", "resource", t("Guides RowMotion AI", "RowMotion AI guides", "أدلة RowMotion AI"), t("Apprenez à filmer, importer et lire une analyse technique.", "Learn how to film, import and read a technical analysis.", "تعلّم كيفية التصوير والرفع وقراءة التحليل التقني.")),
  page("about", "company", t("À propos de RowMotion AI", "About RowMotion AI", "حول RowMotion AI"), t("Une plateforme conçue pour rendre l’analyse technique d’aviron plus accessible et structurée.", "A platform built to make rowing technique analysis more accessible and structured.", "منصة صُممت لجعل تحليل تقنية التجديف أكثر سهولة وتنظيماً.")),
  page("pricing", "company", t("Tarifs RowMotion AI", "RowMotion AI pricing", "أسعار RowMotion AI"), t("Découvrez les espaces athlète, coach et club. Les offres commerciales définitives seront publiées sans prix fictifs.", "Explore athlete, coach and club workspaces. Final commercial offers will be published without fabricated pricing.", "اكتشف مساحات الرياضي والمدرب والنادي. ستُنشر العروض النهائية دون أسعار وهمية.")),
  page("faq", "company", t("Questions fréquentes", "Frequently asked questions", "الأسئلة الشائعة"), t("Réponses sur l’analyse vidéo, la caméra, les formats et la protection des données.", "Answers about video analysis, camera use, formats and data protection.", "إجابات حول تحليل الفيديو والكاميرا والصيغ وحماية البيانات.")),
  page("contact", "company", t("Contacter RowMotion AI", "Contact RowMotion AI", "تواصل مع RowMotion AI"), t("Demandez une démonstration ou présentez les besoins de votre club.", "Request a demonstration or describe your club’s needs.", "اطلب عرضاً توضيحياً أو اشرح احتياجات ناديك.")),
  page("privacy", "legal", t("Politique de confidentialité", "Privacy policy", "سياسة الخصوصية"), t("Informations sur les comptes, profils sportifs, vidéos, mesures et droits des utilisateurs.", "Information about accounts, sports profiles, videos, measurements and user rights.", "معلومات حول الحسابات والملفات الرياضية والفيديوهات والقياسات وحقوق المستخدمين.")),
  page("terms", "legal", t("Conditions d’utilisation", "Terms of use", "شروط الاستخدام"), t("Règles applicables à l’utilisation responsable de la plateforme.", "Rules governing responsible use of the platform.", "القواعد المنظمة للاستخدام المسؤول للمنصة.")),
  page("cookies", "legal", t("Politique relative aux cookies", "Cookie policy", "سياسة ملفات تعريف الارتباط"), t("Gestion du stockage essentiel et du consentement aux outils de mesure facultatifs.", "Management of essential storage and consent for optional measurement tools.", "إدارة التخزين الضروري والموافقة على أدوات القياس الاختيارية.")),
];
export function getPublicPage(path: string) { return publicPages.find((item) => item.path === path); }
