import { addDoc, collection, doc, documentId, getDoc, getDocs, query, serverTimestamp, updateDoc, where, writeBatch } from "firebase/firestore";
import { auth, db } from "@/lib/firebase";
import { createUserProfile } from "@/services/auth-service";
import type { Club } from "@/types/club";
import type { UserProfile, UserRole } from "@/types/user";

function requireSession() { if (!auth?.currentUser || !db) throw new Error("Session Firebase indisponible."); return { user: auth.currentUser, database: db }; }
function assertManager(profile: UserProfile) { if (!profile.active || !["club_admin", "superadmin"].includes(profile.role)) throw new Error("Vous n’êtes pas autorisé à gérer ces relations."); }
function normalizeClub(id: string, data: Record<string, unknown>): Club { return { id, name: typeof data.name === "string" ? data.name : "Club sans nom", shortName: typeof data.shortName === "string" ? data.shortName : null, logoUrl: typeof data.logoUrl === "string" ? data.logoUrl : null, city: typeof data.city === "string" ? data.city : null, country: typeof data.country === "string" ? data.country : null, email: typeof data.email === "string" ? data.email : null, phone: typeof data.phone === "string" ? data.phone : null, active: data.active === true, createdBy: typeof data.createdBy === "string" ? data.createdBy : "", createdAt: data.createdAt, updatedAt: data.updatedAt }; }

export async function listClubs(profile: UserProfile): Promise<Club[]> { const { database } = requireSession(); const base = collection(database, "clubs"); const snapshot = profile.role === "superadmin" ? await getDocs(base) : profile.clubId ? await getDocs(query(base, where(documentId(), "==", profile.clubId))) : null; return snapshot ? snapshot.docs.map((item) => normalizeClub(item.id, item.data())) : []; }
export async function getClub(clubId: string, profile: UserProfile): Promise<Club> { const { database } = requireSession(); if (profile.role !== "superadmin" && profile.clubId !== clubId) throw new Error("Club introuvable."); const snapshot = await getDoc(doc(database, "clubs", clubId)); if (!snapshot.exists()) throw new Error("Club introuvable."); return normalizeClub(snapshot.id, snapshot.data()); }
export async function createClub(profile: UserProfile, values: Omit<Club, "id" | "createdBy" | "createdAt" | "updatedAt" | "logoUrl">) { const { database, user } = requireSession(); if (profile.role !== "superadmin") throw new Error("Accès réservé au Super administrateur."); const reference = await addDoc(collection(database, "clubs"), { ...values, logoUrl: null, createdBy: user.uid, createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); return reference.id; }

export async function listManagedUsers(profile: UserProfile, role?: UserRole): Promise<UserProfile[]> { const { database } = requireSession(); const constraints = role ? [where("role", "==", role)] : []; if (profile.role !== "superadmin") { if (!profile.clubId) return []; constraints.push(where("clubId", "==", profile.clubId)); } const snapshot = await getDocs(query(collection(database, "users"), ...constraints)); return snapshot.docs.map((item) => createUserProfile(item.id, typeof item.data().email === "string" ? item.data().email : null, item.data())); }

export async function setMemberClub(manager: UserProfile, memberId: string, clubId: string | null) { assertManager(manager); const { database } = requireSession(); if (manager.role === "club_admin" && manager.clubId !== clubId && clubId !== null) throw new Error("Vous ne pouvez gérer que votre club."); const target = await getDoc(doc(database, "users", memberId)); if (!target.exists()) throw new Error("Profil utilisateur introuvable."); const targetProfile = createUserProfile(target.id, typeof target.data().email === "string" ? target.data().email : null, target.data()); if (manager.role === "club_admin" && targetProfile.clubId && targetProfile.clubId !== manager.clubId) throw new Error("Cet utilisateur ne fait pas partie de votre club."); await updateDoc(target.ref, { clubId, updatedAt: serverTimestamp() }); }

export async function associateCoachAthlete(manager: UserProfile, athleteId: string, coachId: string) {
  assertManager(manager); const { database } = requireSession(); const [athleteSnapshot, coachSnapshot] = await Promise.all([getDoc(doc(database, "users", athleteId)), getDoc(doc(database, "users", coachId))]);
  if (!athleteSnapshot.exists()) throw new Error("Profil athlète introuvable."); if (!coachSnapshot.exists()) throw new Error("Profil coach introuvable.");
  const athlete = createUserProfile(athleteSnapshot.id, null, athleteSnapshot.data()); const coach = createUserProfile(coachSnapshot.id, null, coachSnapshot.data());
  if (athlete.role !== "athlete" || coach.role !== "coach") throw new Error("Impossible d’associer ces deux utilisateurs.");
  if (!athlete.clubId || athlete.clubId !== coach.clubId) throw new Error("Le coach et l’athlète doivent appartenir au même club.");
  if (manager.role === "club_admin" && manager.clubId !== athlete.clubId) throw new Error("Cet athlète ne fait pas partie de votre club.");
  const batch = writeBatch(database); batch.update(athleteSnapshot.ref, { coachId, updatedAt: serverTimestamp() });
  const coachNotice = doc(collection(database, "notifications")); batch.set(coachNotice, { userId: coachId, type: "athlete_assigned", title: "Nouvel athlète", message: "Un nouvel athlète vous a été associé.", read: false, href: `/athletes/${athleteId}`, createdAt: serverTimestamp() });
  const athleteNotice = doc(collection(database, "notifications")); batch.set(athleteNotice, { userId: athleteId, type: "coach_assigned", title: "Coach associé", message: "Votre coach a été associé à votre profil.", read: false, href: "/mon-coach", createdAt: serverTimestamp() });
  await batch.commit();
}

export async function createCoachInvitation(manager: UserProfile, input: { email: string; firstName: string; lastName: string; phone: string; licenseNumber: string; specialty: string; birthDate: string; clubId: string; active: boolean }) { assertManager(manager); const { database, user } = requireSession(); const clubId = manager.role === "club_admin" ? manager.clubId : input.clubId; if (!clubId) throw new Error("Sélectionnez un club."); if (manager.role === "club_admin" && clubId !== manager.clubId) throw new Error("Vous ne pouvez inviter que dans votre club."); const reference = await addDoc(collection(database, "coachInvitations"), { ...input, email: input.email.trim().toLowerCase(), clubId, requestedBy: user.uid, status: "pending_admin_sdk", createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); return reference.id; }
