"use client";
import { useEffect,useState } from "react";
import { CalendarDays,Download,Flame,Gauge,Star,Timer,Waves,Zap } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { ProtectedPage } from "@/components/ProtectedPage";
import { useAuth } from "@/providers/AuthProvider";
import { listAnalyses } from "@/services/analysis-service";
import type { RowingAnalysis } from "@/types/analysis";

function ProgressChart(){const points=[220,245,280,284,283,285,280,278,300,291,299,283,284];const path=points.map((value,index)=>`${index?"L":"M"} ${20+index*65} ${160-(value-200)*.7}`).join(" ");return <div className="progress-main-chart"><svg viewBox="0 0 820 190"><g>{[35,75,115,155].map((y)=><line key={y} x1="20" y1={y} x2="800" y2={y}/>)}</g><path d={path}/>{points.map((value,index)=><circle key={index} cx={20+index*65} cy={160-(value-200)*.7} r="4"/>)}</svg><div>{["24 Fév","3 Mar","10 Mar","17 Mar","24 Mar","31 Mar","7 Avr","14 Avr","21 Avr","28 Avr","5 Mai","12 Mai","18 Mai"].map((label)=><span key={label}>{label}</span>)}</div></div>}
function ProgressionContent(){const {profile}=useAuth();const [items,setItems]=useState<RowingAnalysis[]>([]);useEffect(()=>{if(profile)void listAnalyses(profile).then(setItems);},[profile]);if(!profile)return null;const completed=items.filter((item)=>item.status==="completed");const score=completed.length?completed.reduce((sum,item)=>sum+(item.technicalScore??0),0)/completed.length/10:8.2;
return <AppShell referenceMode title="Progression" subtitle="Suivez votre évolution et analysez vos performances dans le temps." headerActions={<><select className="header-select"><option>Période · 12 semaines</option></select><button className="button ghost"><Download/>Exporter le rapport</button></>}>
  <div className="progress-reference"><nav className="directory-tabs"><button className="active">Vue d’ensemble</button><button>Performances</button><button>Technique</button><button>Puissance</button><button>Endurance</button><button>Comparaison</button></nav>
  <section className="progress-stats">{([[Waves,"Distance totale","1,248","km","8%"],[Timer,"Temps total","58h 24m","","8%"],[Zap,"Puissance moyenne","268","w","7%"],[Star,"Score technique moyen",score.toFixed(1),"/10","0.6"],[CalendarDays,"Séances",items.length||42,"","12%"],[Flame,"Calories brûlées","18,420","kcal","9%"]] as const).map(([Icon,label,value,unit,trend])=><article key={String(label)}><Icon/><span><small>{label}</small><strong>{value}<i>{unit}</i></strong><em>↑ {trend} <b>vs période précédente</b></em></span></article>)}</section>
  <div className="progress-layout"><main><section className="progress-chart-card"><div className="reference-card-title"><h2>Évolution des performances</h2><nav><button>4 semaines</button><button className="active">12 semaines</button><button>6 mois</button><button>1 an</button></nav></div><div className="chart-legend"><span>━ Puissance (W)</span><span>━ Cadence (spm)</span><span>━ Score technique (/10)</span><span>━ Allure (/500m)</span></div><ProgressChart/></section>
  <div className="progress-duo"><section><h2>Répartition par zones d’entraînement</h2><div className="progress-zones"><div className="mini-directory-donut"/><ul><li>UT2 <strong>45% · 18h 24m</strong></li><li>UT1 <strong>25% · 10h 12m</strong></li><li>AT <strong>15% · 6h 18m</strong></li><li>TR <strong>10% · 4h 12m</strong></li><li>AN <strong>5% · 2h 06m</strong></li></ul></div><p className="progress-good">♧ Équilibre excellent <small>Votre répartition par zones est bien équilibrée.</small></p></section><section><div className="reference-card-title"><h2>Évolution de la distance</h2><select><option>Distance (km)</option></select></div><div className="bar-progress-chart">{[120,145,190,180,198,210,198,198,215,235,205,195].map((height,index)=><i key={index} style={{height:`${height/2.4}px`}}/>)}</div><div className="distance-summary">{[["Distance moyenne / semaine","104 km"],["Meilleure semaine","156 km"],["Dernière semaine","128 km"],["Objectif hebdo","120 km"]].map(([label,value])=><span key={label}><small>{label}</small><strong>{value}</strong></span>)}</div></section></div>
  <section className="records-card"><h2>Records personnels</h2><div>{[["Distance (2K)","7:12.4"],["Allure (500m)","1:48.3"],["Puissance max","612 w"],["Cadence max","38 spm"],["Score technique","9.1/10"],["Temps (30 min)","7,320 m"]].map(([label,value])=><article key={label}><Gauge/><small>{label}</small><strong>{value}</strong><span>Nouveau record</span></article>)}</div><a>Voir tous mes records →</a></section></main>
  <aside className="progress-sidebar"><section><h2>Résumé de progression</h2><div className="progress-ring">78%</div><strong>Progression globale</strong><em>Très bonne progression !</em><p>Vous êtes sur la bonne voie pour atteindre vos objectifs.</p>{["Puissance ↑ 7%","Endurance ↑ 10%","Technique ↑ 6%","Régularité ↑ 12%","Explosivité ↑ 5%"].map((row)=><span key={row}>{row}</span>)}</section><section><div className="reference-card-title"><h2>Meilleures séances</h2><a>Voir toutes</a></div>{["Séance du 18 Mai 2025","Séance du 10 Mai 2025","Séance du 3 Mai 2025"].map((name,index)=><article key={name}><Waves/><p><strong>{name}</strong><small>20:45 · 6,310 m · 268 w</small></p><em>{[8.7,8.3,8.1][index]}/10</em></article>)}</section><section><h2>Analyse comparative</h2><p>Par rapport à des athlètes de votre niveau</p><div className="comparison-rings"><span>+12%<small>Puissance</small></span><span>+8%<small>Endurance</small></span><span>+5%<small>Technique</small></span></div></section></aside></div></div>
</AppShell>;}
export default function ProgressionPage(){return <ProtectedPage><ProgressionContent/></ProtectedPage>;}
