import { StrictMode } from "react";import { act,cleanup,fireEvent,render,screen } from "@testing-library/react";import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { detectIosSafari,detectStandalone,PwaInstallProvider } from "@/components/pwa/PwaInstallProvider";import { usePwaInstall } from "@/hooks/use-pwa-install";import { getSafeNextPath } from "@/lib/navigation/safe-next-path";import type { BeforeInstallPromptEvent } from "@/types/pwa";
class InstallEvent extends Event implements BeforeInstallPromptEvent{readonly platforms=["web"];readonly prompt=vi.fn(async()=>undefined);readonly userChoice:Promise<{outcome:"accepted"|"dismissed";platform:string}>;constructor(outcome:"accepted"|"dismissed"){super("beforeinstallprompt");this.userChoice=Promise.resolve({outcome,platform:"web"});}}
function Consumer(){const value=usePwaInstall();return <><span data-testid="can">{String(value.canInstall)}</span><span data-testid="installed">{String(value.isInstalled)}</span><span data-testid="outcome">{value.installOutcome??"none"}</span><button onClick={()=>void value.install()}>install</button></>}
const media={matches:false,media:"(display-mode: standalone)",onchange:null,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn(),dispatchEvent:vi.fn()};
beforeEach(()=>{Object.defineProperty(window,"matchMedia",{writable:true,value:vi.fn(()=>media)});Object.defineProperty(window.navigator,"standalone",{configurable:true,value:false});});afterEach(()=>{cleanup();vi.clearAllMocks();});
describe("PWA installation",()=>{
it("detects standalone and iOS Safari",()=>{expect(detectStandalone()).toBe(false);media.matches=true;expect(detectStandalone()).toBe(true);media.matches=false;expect(detectIosSafari("Mozilla/5.0 (iPhone) AppleWebKit Safari/605.1")).toBe(true);expect(detectIosSafari("Mozilla/5.0 Chrome Safari")).toBe(false);});
it.each(["accepted","dismissed"] as const)("handles %s",async outcome=>{render(<PwaInstallProvider><Consumer/></PwaInstallProvider>);const event=new InstallEvent(outcome);act(()=>window.dispatchEvent(event));expect(screen.getByTestId("can")).toHaveTextContent("true");fireEvent.click(screen.getByText("install"));await act(async()=>{await event.userChoice;});expect(event.prompt).toHaveBeenCalledOnce();expect(screen.getByTestId("outcome")).toHaveTextContent(outcome);expect(screen.getByTestId("can")).toHaveTextContent("false");});
it("returns unavailable without a browser prompt",async()=>{render(<PwaInstallProvider><Consumer/></PwaInstallProvider>);fireEvent.click(screen.getByText("install"));await act(async()=>undefined);expect(screen.getByTestId("outcome")).toHaveTextContent("unavailable");});
it("throws when the hook has no provider",()=>{function Missing(){usePwaInstall();return null;}expect(()=>render(<Missing/>)).toThrow("usePwaInstall must be used inside PwaInstallProvider");});
it("cleans listeners and remains idempotent in Strict Mode",()=>{const add=vi.spyOn(window,"addEventListener");const remove=vi.spyOn(window,"removeEventListener");const view=render(<StrictMode><PwaInstallProvider><Consumer/></PwaInstallProvider></StrictMode>);view.unmount();const beforeAdds=add.mock.calls.filter(([name])=>name==="beforeinstallprompt").length;const beforeRemoves=remove.mock.calls.filter(([name])=>name==="beforeinstallprompt").length;expect(beforeAdds).toBe(beforeRemoves);expect(media.addEventListener.mock.calls.length).toBe(media.removeEventListener.mock.calls.length);});
});
describe("safe next path",()=>{it("accepts local paths",()=>expect(getSafeNextPath("/analyses/123")).toBe("/analyses/123"));it("rejects external and protocol-relative paths",()=>{expect(getSafeNextPath("https://evil.test")).toBe("/dashboard");expect(getSafeNextPath("//evil.test")).toBe("/dashboard");});});
