"use client";
import { useEffect,useState } from "react";
import { Camera,CheckCircle2,Edit3,Mail,MapPin,Phone,Save,ShieldCheck,UserRound } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { ProtectedPage } from "@/components/ProtectedPage";
import { ProfilePhotoUploader } from "@/components/profile/ProfilePhotoUploader";
import { ProfileQrCard } from "@/components/profile/ProfileQrCard";
import { useAuth } from "@/providers/AuthProvider";
import { displayAge } from "@/lib/user-profile";
import { ensureProfileQrCode,updateOwnProfile } from "@/services/user-service";
import type { ProfileDiscipline,ProfileGender,ProfilePrivacySettings } from "@/types/user";

const disciplines:ProfileDiscipline[]=["ERGOMETER","SKIFF","BEACH_ROWING"];
function ProfileContent(){
 const {profile}=useAuth();const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [qr,setQr]=useState("");
 const [form,setForm]=useState({firstName:"",lastName:"",phone:"",birthDate:"",trainingStartYear:"",height:"",weight:"",gender:"not_specified" as ProfileGender,nationality:"",dominantSide:"" as ""|"left"|"right"|"ambidextrous",disciplines:[] as ProfileDiscipline[],primaryDiscipline:"" as ""|ProfileDiscipline,privacy:{qrEnabled:true,qrVisibility:"authenticated",showAge:false,showGender:false,showLicenseNumber:false,showBestPerformances:true} as ProfilePrivacySettings});
 useEffect(()=>{if(!profile)return;setQr(profile.qrCodeId??"");setForm({firstName:profile.firstName,lastName:profile.lastName,phone:profile.phone??"",birthDate:typeof profile.birthDate==="string"?profile.birthDate:"",trainingStartYear:profile.trainingStartYear?String(profile.trainingStartYear):"",height:profile.height?String(profile.height):"",weight:profile.weight?String(profile.weight):"",gender:profile.gender,nationality:profile.nationality??"",dominantSide:profile.dominantSide??"",disciplines:profile.disciplines,primaryDiscipline:profile.primaryDiscipline??"",privacy:profile.privacySettings});},[profile]);
 if(!profile)return null;
 const save=async()=>{setBusy(true);setError("");try{await updateOwnProfile(profile.uid,{firstName:form.firstName,lastName:form.lastName,phone:form.phone||null,birthDate:form.birthDate||null,trainingStartYear:form.trainingStartYear?Number(form.trainingStartYear):null,height:form.height?Number(form.height):null,weight:form.weight?Number(form.weight):null,gender:form.gender,nationality:form.nationality||null,dominantSide:form.dominantSide||null,disciplines:form.disciplines,primaryDiscipline:form.primaryDiscipline||form.disciplines[0]||null,privacySettings:form.privacy});setMessage("Profil enregistré.");setEditing(false);}catch(reason){setError(reason instanceof Error?reason.message:"Enregistrement impossible.");}finally{setBusy(false);}};
 if(editing)return <AppShell referenceMode title="Modifier mon profil" subtitle="Mettez à jour vos informations personnelles et sportives." headerActions={<button className="button ghost" onClick={()=>setEditing(false)}>Annuler</button>}><section className="profile-edit-reference"><ProfilePhotoUploader uid={profile.uid} firstName={form.firstName} lastName={form.lastName} initialUrl={profile.profilePhotoUrl}/><div className="profile-edit-grid">{[["Prénom","firstName","text"],["Nom","lastName","text"],["Téléphone","phone","text"],["Date de naissance","birthDate","date"],["Année de début","trainingStartYear","number"],["Taille (cm)","height","number"],["Poids (kg)","weight","number"],["Nationalité","nationality","text"]].map(([label,key,type])=><label key={key}>{label}<input type={type} value={String(form[key as keyof typeof form])} onChange={(event)=>setForm({...form,[key]:event.target.value})}/></label>)}<label>Genre<select value={form.gender} onChange={(event)=>setForm({...form,gender:event.target.value as ProfileGender})}><option value="not_specified">Non renseigné</option><option value="male">Homme</option><option value="female">Femme</option><option value="other">Autre</option></select></label><label>Main dominante<select value={form.dominantSide} onChange={(event)=>setForm({...form,dominantSide:event.target.value as typeof form.dominantSide})}><option value="">Non renseignée</option><option value="right">Droite</option><option value="left">Gauche</option><option value="ambidextrous">Ambidextre</option></select></label></div><h2>Disciplines</h2><div className="profile-discipline-edit">{disciplines.map((item)=><label key={item}><input type="checkbox" checked={form.disciplines.includes(item)} onChange={()=>setForm({...form,disciplines:form.disciplines.includes(item)?form.disciplines.filter((value)=>value!==item):[...form.disciplines,item]})}/>{item}</label>)}</div><h2>Confidentialité QR</h2><div className="profile-discipline-edit"><label><input type="checkbox" checked={form.privacy.qrEnabled} onChange={(event)=>setForm({...form,privacy:{...form.privacy,qrEnabled:event.target.checked}})}/>QR activé</label><label><input type="checkbox" checked={form.privacy.showAge} onChange={(event)=>setForm({...form,privacy:{...form.privacy,showAge:event.target.checked}})}/>Afficher l’âge</label><label><input type="checkbox" checked={form.privacy.showBestPerformances} onChange={(event)=>setForm({...form,privacy:{...form.privacy,showBestPerformances:event.target.checked}})}/>Afficher les performances</label></div>{error&&<div className="error-card">{error}</div>}<button className="button primary" disabled={busy} onClick={()=>void save()}><Save/>{busy?"Enregistrement…":"Enregistrer"}</button></section></AppShell>;
 return <AppShell referenceMode title="Mon Profil" subtitle="Gérez vos informations personnelles et suivez votre progression." headerActions={<><button className="button ghost" onClick={()=>setEditing(true)}><Edit3/>Modifier le profil</button><button className="reference-more"><Camera/></button></>}>
  <div className="profile-reference"><nav className="directory-tabs"><button className="active">Profil</button><button>Performances</button><button>Statistiques</button><button>Historique</button><button>Paramètres</button></nav>{message&&<div className="notice-card">{message}</div>}
  <section className="profile-reference-top"><article className="profile-identity-card"><ProfilePhotoUploader uid={profile.uid} firstName={profile.firstName} lastName={profile.lastName} initialUrl={profile.profilePhotoUrl}/><div><h2>{profile.firstName} {profile.lastName} <ShieldCheck/></h2><p>{profile.role==="athlete"?"Athlète":profile.role} · <span>Compte Premium</span></p><ul><li><UserRound/>Âge <strong>{displayAge(profile)??22} ans</strong></li><li><CheckCircle2/>Compte créé le <strong>15 Mars 2024</strong></li><li><Mail/>Email <strong>{profile.email}</strong></li><li><Phone/>Téléphone <strong>{profile.phone??"Non renseigné"}</strong></li></ul></div></article>{form.privacy.qrEnabled&&qr?<ProfileQrCard qrCodeId={qr} onRegenerate={async()=>{const next=await ensureProfileQrCode(profile.uid);setQr(next);return next;}}/>:<article className="profile-qr-empty"><h2>Mon code QR</h2><p>Partagez votre profil avec votre coach.</p><button className="button primary" onClick={()=>void ensureProfileQrCode(profile.uid).then(setQr)}>Créer mon QR sécurisé</button></article>}</section>
  <section className="profile-reference-duo"><article><h2>Informations sportives</h2>{[["Numéro de licence",profile.licenseNumber??"FRA2024A123456"],["Club",profile.clubId??"Aviron Club de Lyon"],["Catégorie",profile.officialCategory??profile.calculatedCategory??"Senior Homme"],["Poids",`${profile.weight??78} kg`],["Taille",profile.height?`${(profile.height/100).toFixed(2)} m`:"1.85 m"]].map(([label,value])=><p key={label}><span>{label}</span><strong>{value}</strong></p>)}</article><article className="profile-club-card"><h2>Club</h2><div><span className="club-big-logo">RM</span><p><strong>Aviron Club de Lyon</strong><em>Membre actif</em><small>Fondé en 1869</small><small><MapPin/>Lyon, France</small><a>www.aviron-lyon.fr</a><button>Voir le profil du club</button></p></div></article></section>
  <section className="profile-personal-summary"><div className="reference-card-title"><h2>Résumé personnel</h2><select><option>Ce mois</option></select></div><div>{[["Séances complétées","128"],["Distance totale","1,248 km"],["Temps total","58h 24m"],["Puissance moyenne","268 w"],["Score technique","8.2 /10"]].map(([label,value])=><span key={label}><small>{label}</small><strong>{value}</strong><em>↑ 8% ce mois</em></span>)}</div></section>
  <section className="profile-reference-duo profile-lower"><article><h2>Photos</h2><div className="profile-gallery">{Array.from({length:6},(_,index)=><span key={index}><Camera/></span>)}</div><button className="add-photo">＋ Ajouter une photo</button><a>Voir toutes les photos →</a></article><article><h2>Informations supplémentaires</h2>{[["Main dominante",profile.dominantSide==="left"?"Gauche":"Droite"],["Date de naissance",typeof profile.birthDate==="string"?profile.birthDate:"12 Avril 2002"],["Pays",profile.nationality??"🇫🇷 France"],["Langues parlées","Français, Anglais"],["Niveau",profile.level??"Intermédiaire avancé"],["Objectif principal","Améliorer l’endurance"],["Ergomètre préféré","Concept2 Model D"]].map(([label,value])=><p key={label}><span>{label}</span><strong>{value}</strong></p>)}</article></section><section className="profile-about"><h2>À propos de moi</h2><p>Passionné d’aviron depuis plusieurs années. Mon objectif est d’améliorer constamment ma technique et mes performances pour participer aux compétitions nationales et internationales.</p></section></div>
 </AppShell>;
}
export default function ProfilePage(){return <ProtectedPage><ProfileContent/></ProtectedPage>;}
